baseURL: "https://mdk84.github.io"
languageCode: "en-us"
title: "MDK"
theme: "PaperMod"
enableRobotsTXT: true

params:
    env: production
    defaultTheme: auto
    profileMode:
            enabled: true
            title: "Hi, I'm MDK." # optional default will be site title
            subtitle: "You can follow me in this platforms:"
            imageUrl: "https://avatars.githubusercontent.com/u/66082748?v=4" # optional
            imageTitle: "My profile" # optional
            imageWidth: 120 # custom size
            imageHeight: 120 # custom size
            buttons:
                - name: Source in Github
                  url: "https://github.com/MDK84/MDK84.github.io"
    socialIcons: # optional
        - name: "Email"
          url: "mailto:mdk84@duck.com"
        - name: "Github"
          url: "https://github.com/MDK84"
        - name: "Twitter"
          url: "https://twitter.com/MDK_84"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/m-dk-535997242/"
        - name: "StackOverFlow"
          url: "https://stackoverflow.com/users/14660291/m-dk"
    
    ShowBreadCrumbs: true
    ShowReadingTime: true
    ShowShareButtons: false
    ShowCodeCopyButtons: true
    comments: true

menu :
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: englishposts
          name: English Posts
          url: /English Posts/
          weight: 20
        - identifier: farsiposts
          name: Farsi Posts
          url: /Farsi Posts/
          weight: 30
        - identifier: aboutme
          name: About me
          url: /aboutme/
          weight: 40
        - identifer: search
          name: Search
          url: /search/
          weight: 50
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
