baseURL: https://mdk84.github.io
languageCode: en-us
build:
  writeStats: true
params:
  title: MDK's Blog
  author: Me
  description: MDK's personal blog
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "x", "reddit", "telegram"]
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
              <link rel="manifest" href="/static/favicon/site.webmanifest">
              <link rel="shortcut icon" href="/static/favicon/favicon.ico">

  profile:
    name: "MDK"
    tagline: A student
    # location: "Earth"
    photo: "/static/images/profile.jpg"
  social:
    title: Links
    list:
      - icon: fa-envelope
        url: "mailto:mdk84@duck.com"
        title: Email
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/m-dk-535997242/"
        title: LinkedIn
      - icon: fab fa-stack-overflow
        url: "https://stackoverflow.com/users/14660291/m-dk"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/MDK84"
        title: GitHub
      - icon: fab fa-twitter
        url: "https://twitter.com/MDK_84"
        title: Twitter
      # - icon: fab fa-orcid
      #   url: "#"
      #   title: Orcid
      # - icon: ai ai-google-scholar
      #   url: "#"
      #   title: Google Scholar
      # - icon: fab fa-researchgate
      #   url: "#"
      #   title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: "Hello there. I’m MDK. I’m :
        a student
        a programmer
        a gamer
        interested in Python"
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Job Title
        dates: 2019 - *Present*
        company: Company Name
        details: |1-
          - Printed from desktop. Sent [emails](#).
              - Called people *using* telephone.
          - Drank water from office cooler.
          - Ate donuts on people's birthdays.
      - position: Job Title
        dates: 2018 - 2019
        url: "#"
        company: Company Name
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Diploma in science
        college: Allame Amini Highschool
        dates: 2021 - 2024
        # thesis_title: "Final Exams"
        # thesis_url: "#"
      # - degree: M.S. in Subject
      #   college: University of State-City
      #   dates: 2013 - 2018
      #   thesis_title: "Effect of humans on other humans: a study of human behavior."
      #   thesis_url: "#"
      # - degree: B.S. in Subject
      #   college: University of State-City
      #   dates: 2004 - 2009
  # publication:
  #   title: Publications
  #   icon: fas fa-book
  #   format:
  #     - date
  #     - title
  #     - authors
  #     - journal
  #   types:
  #     - Journal Articles
  #     - Proceedings
  #   list:
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Project 1
        url: "#"
        description: Nothing
      # - title: Project 2
      #   url: "#"
      #   description: Description of the project
      # - title: Project 3
      #   url: "#"
      #   description: Description of the project
      # - title: Project 4
      #   url: "#"
      #   description: Description of the project
  skill:
    title: To do list
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "12th year of studying"
        skillrating: 100
      - skill: Waiting for the exam's result
        skillrating: 25
      # - skill: Skill 4
      #   skillrating: 50
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Playing video games
      - hobby: Listening to music
      - hobby: Learning English
menu :
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: englishposts
          name: English Posts
          url: /English Posts/
          weight: 20
        - identifier: farsiposts
          name: Farsi Posts
          url: /Farsi Posts/
          weight: 30
        - identifer: search
          name: Search
          url: /search/
          weight: 50